name: phpMyBlog
services:
  webserver:
    container_name: webserver
    build: .
    ports:
      - "80:80"
      - "8025:8025"
    volumes:
      - ./website/:/sites/localhost/html/public/
#      - ./docker/etc/:/docker/etc/
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
#      - ./docker/data/conf.d:/etc/mysql/conf.d
#      - ./docker/data/logs:/logs
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  adminpanel:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  db_data:
